controller_list:
  - name: fake_warthog_arm_controller
    joints:
      - id_1
      - id_2
      - id_3
      - id_4
      - id_5
initial:  # Define initial robot poses.
  - group: warthog_arm
    pose: Rest