controller_list:
  - name: arm_controller  #"arm"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - id_1
      - id_2
      - id_3
      - id_4
      - id_5