joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

#arm:
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - id_1
     - id_2
     - id_3
     - id_4
     - id_5
     
  gains:
      id_1: { p: 100, d: 1, i: 1, i_clamp: 1 }
      id_2: { p: 100, d: 1, i: 1, i_clamp: 1 }
      id_3: { p: 100, d: 1, i: 1, i_clamp: 1 }
      id_4: { p: 100, d: 1, i: 1, i_clamp: 1 }
      id_5: { p: 100, d: 1, i: 1, i_clamp: 1 }
      
  
  state_publish_rate: 25 